version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: essay-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: essay
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3308"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - essayapp-network

networks:
  essayapp-network:
    driver: bridge
